services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: kumaroid
      POSTGRES_PASSWORD: kumaroid
      POSTGRES_DB: snowflake
    ports:
      - '5434:5432'
    volumes:
      - './init/:/docker-entrypoint-initdb.d/'
      - './data:/data'
      - './transform:/transform'